# Generated by Django 3.0 on 2020-02-25 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, help_text='Este campo é destinado aos usuários de perfil paciente.', related_name='favorites', to='medicSearch.Speciality', verbose_name='Favoritos'),
        ),
        migrations.AlterField(
            model_name='address',
            name='neighborhood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhood', to='medicSearch.Neighborhood'),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank='False', on_delete=django.db.models.deletion.CASCADE, related_name='state', to='medicSearch.State'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='city',
            field=models.ForeignKey(blank='False', on_delete=django.db.models.deletion.CASCADE, related_name='city', to='medicSearch.City'),
        ),
    ]
