# Generated by Django 3.0 on 2020-02-25 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicSearch', '0002_auto_20200225_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, help_text='Este campo é destinado aos usuários de perfil paciente.', related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Favoritos'),
        ),
    ]
