# Generated by Django 2.2.7 on 2019-11-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0002_auto_20191126_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='addresses',
            field=models.ManyToManyField(related_name='addresses', to='medicSearch.Address'),
        ),
    ]
