# Generated by Django 3.0 on 2020-02-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0003_auto_20200225_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
