# Generated by Django 2.2.7 on 2019-11-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0003_profile_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='addresses',
            field=models.ManyToManyField(null=True, related_name='addresses', to='medicSearch.Address'),
        ),
    ]
