# Generated by Django 2.2.7 on 2019-11-26 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0004_auto_20191126_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='specialties',
            field=models.ManyToManyField(null=True, related_name='specialties', to='medicSearch.Speciality'),
        ),
    ]
