# Generated by Django 3.0.3 on 2020-05-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicSearch', '0004_address_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='opinion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
